# Generated by Django 5.2.4 on 2025-08-17 01:40

import communities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "verbose_name": "Community Membership",
                "verbose_name_plural": "Community Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Community Post",
                "verbose_name_plural": "Community Posts",
            },
        ),
        migrations.AlterField(
            model_name="community",
            name="color",
            field=models.CharField(
                default=communities.models.generate_random_color,
                help_text="HSL color for the community planet in space visualization",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this community was created"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(
                help_text="Detailed description of what this community is about"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="is_parent",
            field=models.BooleanField(
                default=True,
                help_text="Is this a parent community? (False for subcommunities)",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent community (leave blank for top-level communities)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcommunities",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title (auto-generated)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="title",
            field=models.CharField(
                help_text="The name of the community (e.g., 'Calculus', 'Computer Science')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this community was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="community",
            field=models.ForeignKey(
                help_text="The community this user is a member of",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this user joined the community"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                help_text="The user who is a member of this community",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                help_text="The user who created this post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                help_text="The community where this post was made",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="The text content of the post"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this post was created"
            ),
        ),
    ]
