# Generated by Django 5.1.3 on 2025-08-17 02:29

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_alter_membership_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="color",
            field=models.CharField(
                default=communities.models.generate_random_color,
                help_text="HSL color for the community planet in space visualization",
                max_length=50,
            ),
        ),
    ]
