# Generated by Django 5.2.4 on 2025-08-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="User's biographical information or personal description",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture - if not provided, default astronaut helmet is used",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="university",
            field=models.CharField(
                blank=True,
                help_text="The university this user attends or attended",
                max_length=100,
                null=True,
            ),
        ),
    ]
