# Generated by Django 5.2.4 on 2025-08-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homecontent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Home Page Content",
                "verbose_name_plural": "Home Page Content",
            },
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this content was first created"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="description",
            field=models.TextField(help_text="The main text content for this section"),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title",
            field=models.CharField(
                help_text="The title or heading for this content section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="type",
            field=models.CharField(
                choices=[("home", "Home"), ("base", "Base")],
                help_text="Where this content should appear (home page or base template)",
                max_length=10,
            ),
        ),
    ]
