# Generated by Django 5.1.3 on 2025-01-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="type",
            field=models.CharField(
                choices=[("home", "Home"), ("base", "Base")],
                default="home",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
