# Generated by Django 5.1.3 on 2025-12-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_session", "0003_studyblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyblock",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studyblock",
            name="day_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
