# Generated by Django 5.1.3 on 2025-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_session", "0004_studyblock_date_alter_studyblock_day_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyblock",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyblock",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
